eosdis-nasa/earthdata-pub-dashboard

- app/src/js/utils/format.js
Investigate the possibility of displaying local (to the user) time
See Ticket: [EDPUB-804](https://bugs.earthdata.nasa.gov/browse/EDPUB-804)
---
1. Click on the Conversations tab
2. Click on All filter
3. Type your reply and check the timestamp of when the message was submitted. This should be of the local time.
---
Made changes to one file app/src/js/utils/format.js
> EDPUB-804 Investigate and fixing the local timezone on updatedtime

- CHANGELOG.md
- app/src/css/_base.scss
Removed funny line from dropdown
See Ticket: EDPUB-1179
2. Push out to sit
3. Verify data producer drop-down does not have any grey lines in it.  See issue screenshot for eg.
* [removed funny line from dropdown](b31adac252ccb52d3a10fc16d906ae81d5775e08)
> removed funny line from dropdown

- app/src/js/actions/index.js
- app/src/js/components/Requests/request.js
- app/src/js/components/Workflows/workflow.js
Update dashboard action to call metadata mapping endpoint for export
Designs: Currently, the dashboard action associated with exporting metadata relies on the mapped metadata to already exist as a part of the request details. An additional dynamic metadata mapping endpoint has been added to the API so that the precondition of mapping is no longer required. This task aims to update the export metadata dashboard action to call the API metadata mapping endpoint then use the response to populate and download a JSON file.
See Ticket: [EDPUB-1224](https://bugs.earthdata.nasa.gov/browse/EDPUB-1224)
---
1. Click on requests
2. Click on the Data Product name that already have a form filled up
3. Click on the settings icon on the top left of the page, then click export on the options.
> EDPUB-1224: Update dashboard action to call metadata mapping endpoint for export

- app/src/js/middleware/request.js
Updates the error message to be more generic as errors caught here shouldn't be anything fixable by a user. 
See Ticket: https://bugs.earthdata.nasa.gov/browse/EDPUB-480
---
3. Deploy stack locally
4. Log in to the system
5. Once on the main dashboard, turn off the API docker containers
6. Attempt to create a new request and you should see the new more generic error message at the top of the dashboard
---
> Updating messaging to be generic in case of a failed promise

- app/src/js/components/Comments/comments.js
- app/src/js/components/Forms/form.js
- app/src/js/components/Requests/approval.js
- app/src/js/components/Review/review.js
- app/src/js/reducers/api.js
- app/src/js/utils/privileges.js
- app/src/js/utils/table-config/requests.js
An approach for adding granular privileges by step name. Please let me know your thoughts or if there are any changes needed.
This is a PR to support the GES DISC workflow, specifically to add a "Manager Approval Step" that no other role has access to. The existing functionality supported a "REVIEW" privilege, but any role with that privilege could review. GES DISC requested this to be restricted a bit more.
The change supports passing the current step name to "requestPrivileges", which allows for a bit of logic when returning whether a user can review or not.
See Ticket: https://bugs.earthdata.nasa.gov/browse/GESDISC-246
---
---
_(copy/paste-able change log notes. check the box when the change is …
> feature: granular review step privileges

- app/src/js/components/Forms/form.js
Adds uploaded files to the DAR and DPR Approval page
See Ticket: https://bugs.earthdata.nasa.gov/browse/EDPUB-1215
- https://github.com/eosdis-nasa/earthdata-pub-api/pull/56
- https://github.com/eosdis-nasa/earthdata-pub-forms/pull/32
---
2. Deploy to SIT.
3. View existing DAR or Create a new Request with an uploaded example file
4. Submit the DAR
5. Verify that the uploaded file is listed on the form approval page
> Edpub 1215 approval page upload display

- app/src/js/components/Conversations/conversation.js
- package-lock.json
- package.json
[add description of work done here]
Designs: Conversation Notes Should Wrap
Specific conversation notes (i.e. conversations/id/{id}) should wrap instead of extending past the right of the screen display.
See Ticket: https://bugs.earthdata.nasa.gov/browse/EDPUB-1344
---
1. Conversation Notes Should Wrap
2. Click on Conversations tab -> click on ALL -> if there are any text then it will wrap
> EDPUB-1344: Conversation Notes Should Wrap

- app/src/js/components/FormQuestions/questions.js
- app/src/js/utils/privileges.js
- app/src/js/utils/table-config/requests.js
Dashboard updates for disabling links when a form is daac_only
See Ticket: https://bugs.earthdata.nasa.gov/browse/EDPUB-1333
Related PR:
https://github.com/eosdis-nasa/earthdata-pub-api/pull/131
---
3. In local DB set DAR form to daac_only
4. Create a new request as a data producer and verify that the next step button is not active
5. Navigate to the request page
6. Verify that the next step option is not present there either
> Hiding links to forms that are daac_only

- app/src/js/components/Comments/comments.js
Fixes issue where step comments were not being displayed properly for review steps that weren't directly tied to a form. This was most noticeable in the GES DISC workflow for the UWG/Management/ESDIS review steps.
See Ticket: https://bugs.earthdata.nasa.gov/browse/EDPUB-1381
---
4. Create a new request and select GES DISC as the DAAC
5. Fill out & submit the DPR form or move the form to the UWG Review step from the request page
6. Make a comment on the UWG Review page and save
7. Refresh the page and verify that the comment still displays.
8. Approve the request
9. On the Management Review page leave a comment and reject the approval
10. Verify that the comments on the UWG Review are still correct …
> Addressing issue with step approval comments

- app/src/js/components/DataUpload/overview.js
- app/src/js/components/FormQuestions/FileUploader.js
- app/src/js/components/FormQuestions/questions.js
Front end changes for splitting uploads into sample/documentation buckets
See Ticket: https://bugs.earthdata.nasa.gov/browse/EDPUB-1297
Related PR: https://github.com/eosdis-nasa/earthdata-pub-api/pull/136
---
2. Pull related branches to SIT.
3. Navigate to the request overview page for a new or existing request
4. Select documentation and click upload to select a file
5. Verify that the file shows the correct category in the table after upload
6. Navigate to the DAR form
7. Verify previously uploaded file shows up in the documentation section
8. Attempt to save the form and verify that a red box appears around the sample file question
9. Upload a file to the sample files
10. Save the form and verify that the red box has …
> Edpub 1297 split uploads

- app/src/js/components/Comments/comments.js
Step name was not being passed properly when forms were skipped which resulted in missing comments on the review pages and missing step names on the conversations page. This PR resolves the issue and ensures that the step name is properly passed regardless of whether the form has been filled in or not.
See Ticket: https://bugs.earthdata.nasa.gov/browse/EDPUB-1423
---
3. Start a new request
4. On the request overview page, change the current step to the DPR review step
5. Navigate to the DPR review page
6. Submit a review comment
7. Refresh page
8. Validate that the comment is still visible. 
9. Navigate to the conversations page for the request and validate that the correct step name is associated …
> resolving missing step name when form is incomplete

- app/src/js/components/Auth/index.js
- app/src/js/components/Conversations/conversation.js
EDPub emails are not showing the NASA logo svg. In a quick investigation, it looks like this is due to the fact that Google expects these sort of artifacts to be of a certain type (not svg).
See Ticket: [EDPUB-1352](https://bugs.earthdata.nasa.gov/browse/EDPUB-1352)
---
3. Check if you see the NASA logo in the email notifications
> EDPUB-1352: Fix EDPub NASA Logo in Email Notifications

- app/src/js/App.js
- app/src/js/actions/index.js
- app/src/js/components/FormRequest/index.js
- app/src/js/components/FormRequest/overview.js
- app/src/js/utils/privileges.js
- app/src/js/utils/table-config/requests.js
Dashboard updates for handling DAAC Selection as part of the Accession Workflow.
Related Work:
- https://github.com/eosdis-nasa/earthdata-pub-api/pull/175
Unblocks:
- https://github.com/eosdis-nasa/earthdata-pub-api/pull/147
---
3. Click New Request -> Data Accession Request Submission
4. Move the request ahead to the DAAC Assignment workflow step.
5. Select one or more DAACs to assign & Select
6. Verify that the submission has moved to closed
7. Verify in db viewer of choice that an entry has been added to the code table for each selected DAAC.
---
* Adds Dashboard updates for DAAC Assignment
> Updating dashboard to repurpose daac selection page for daac assignment

- app/src/js/utils/table-config/requests.js
Currently next action button will not display for DAAC staff & Data Producers for filling out forms. This update resolves that.
> Fix submit form missing privilege

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/support_question.md
- .github/pull_request_template.md
- CHANGELOG.md
- README.md
I have updated the pull request and issue templates to try to make the issue / PR process a bit
more contributor / maintainer friendly
JIRA Task: [EDPUB-1478](https://bugs.earthdata.nasa.gov/browse/EDPUB-1478)
2. Test creating a new issue to see if issue templates are available.
3. Test creating a new PR to see if the pull request template is available
> EDPUB-1478: Update repo template assets

- app/src/js/actions/index.js
- app/src/js/components/Conversations/attachment.js
- app/src/js/components/Conversations/conversation.js
- app/src/js/components/Conversations/note.js
Currently, the conversations page will refresh after sending a reply. The backend move attachments operations may not yet be complete resulting in only the note text displaying after the refresh. Determine the best way of resolving this issue and implement.
See Ticket: [EDPUB-1445](https://bugs.earthdata.nasa.gov/browse/EDPUB-1445)
---
3. Navigate to the conversation tab and try adding a new one with attachments. You should see a tooltip until the attachments are processed.
> Edpub-1445: Fix async note refresh issue

- app/src/js/components/Comments/comments.js
GES DISC reported a bug where the step comments entry would fail (error on API call) if the text contained newlines. This behavior is not the case for the conversations tab, so step comments text entry and display was updated to align with the conversations tab.
3. Create a new request.
4. Change the step to a form review step.
5. Add a comment like
```
Hello!
This is a test of using newlines.
Goodbye!
```
6. Send the comment. Ensure that the newlines are displayed as expected after send.
7. Refresh the page.
8. Ensure that the comment and newlines are displayed as expected.
> Hotfix: Fix step comment newlines

- app/src/js/components/Conversations/conversation.js
During testing, Chelsey found that request conversations are occasionally encountering an error while loading. This appears to be caused by the use of state variables and useEffect changing the state variable effectively creating an infinite loop. The task will likely need to update how useEffect is being used in this code block to resolve the issue.
https://eosdis.slack.com/archives/C01JY5B73QC/p1741032198716899
JIRA Task:[ [example](link_here)](https://bugs.earthdata.nasa.gov/browse/EDPUB-1505)
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're …
> Edpub 1505: Investigate Conversations Error

- CHANGELOG.md
- app/src/js/components/DataUpload/overview.js
- app/src/js/components/FormQuestions/FormQuestions.css
- app/src/js/components/FormQuestions/questions.js
Added the ability to remove not yet uploaded files from file list. This allows a user to avoid uploading a file which may have been selected on accident.
JIRA Task: https://bugs.earthdata.nasa.gov/browse/EDPUB-1533
2. Push the related branches to SIT.
3. Go to a request's detail overview page.
4. Select a couple files to upload.
5. Validate that you will now see each file's progress bars by default.
6. Validate that you see a red `Remove` button on the right side.
7. Try removing a couple of the selected files.
8. With at least one file still selected, click the `Upload` button. (Be sure to click a category for the files to be uploaded to)
9. Validate that only the still selected file(s) was uploaded.
10. Navigate to an accession …
> EDPUB-1533: Add delete not yet uploaded file feature

- app/src/js/components/Comments/comments.js
Dashboard was querying API with undefined formId. This would lead to an error mapping to the formId map. To maintain existing functionality, I replicated this erroneous mapping. In the future, we should investigate properly handling this error and display.
JIRA Task: [EDPUB-1513](https://bugs.earthdata.nasa.gov/browse/EDPUB-1513)
3. Create a new request.
4. Create a user with observer role and root group.
5. Move the request to the ESDIS Final Review Step.
6. Open chrome dev tools
7. Navigate to the ESDIS Final Review Step page.
8. Validate that an API call with an undefined formId is not sent.
> EDPUB-1513: Stop Querying API with undefined formId

- .snyk
- app/src/js/components/Review/review.js
Observer role should have the permissions for reviewing outlined in https://wiki.earthdata.nasa.gov/display/EDPUB/EDPub+User+Groups+and+Roles 
Bug discovered when demoing to Info team- root group observer unable to approve DAR form.
3. Create a new request.
4. Change the current step to the DAR review step.
5. Sign in as a root group observer.
6. Navigate to the DAR review page.
7. Confirm you can see the Approve / Return buttons
> Observer role should have review permissions

- app/src/js/components/Requests/request.js
Update dashboard code to name to file downloaded for a metadata export to be derived from the request name.
JIRA Task: [EDPUB-1580](https://bugs.earthdata.nasa.gov/browse/EDPUB-1580)
and validate the expected behavior. (For an example of good validation instructions, check out [Bryan's Bouncy Ball …
> EDPUB-1580: Update downloaded form file name to be derived from request name

- app/src/js/utils/privileges.js
- app/src/js/utils/table-config/requests.js
Chelsey reported an error where the dashboard was missed during the esdis additional review step rename. This is just a hotfix to find/replace those references
3. Create new request
4. Move request ahead to the ESDIS Additional Review Assessment Step
5. Navigate to the step page
6. User should be presented with an option to select whether the dataset needs additional review or not
> Hotfix: Update step name after rename in api

- app/src/js/actions/index.js
- app/src/js/components/DataUpload/overview.js
- app/src/js/components/FormRequest/form.js
- app/src/js/components/Forms/form.js
GES DISC reported an issue with downloading files which upon further investigation is the result of the file location changing due to the reroute feature updates. Upon further investigation, I found we were incorrectly concatenating the file key to the url rather than adding it as a querystring. I also found that we were making an unnecessary call to the downloadUrl endpoint.
2. Push the changes to SIT.
3. Open the network tab and attempt to download a file.
4. Verify that the file key is sent as a query string rather than concatenated to the request url.
5. Verify that only one request is sent to the downloadUrl endpoint (one is also sent to the AWS S3 …
> Hotfix: Fix download url query

- package-lock.json
- package.json
Update EDPub upload utility version to latest to avoid issues with vulnerable sub dependency.
2. Validate that the Snyk blocking step completes successfully
> Hotfix: Update edpub upload utility version to latest
