eosdis-nasa/earthdata-pub-dashboard

- app/src/js/components/Forms/form.js
ViewcommentsList variable already removed. Remove dangling assignment.
> Resolve blank page when reviewing form answers

- .github/workflows/github-actions.yml
Add github actions to run acceptance testing
See Ticket: [EDPUB-1184](https://bugs.earthdata.nasa.gov/browse/EDPUB-1184)
---
1. Confirm test are passing and a condition of merge.
---
Add github actions to run acceptance testing
* [Add _____](link to commitid)
> Edpub 1184 adding GitHub actions

- app/src/js/components/Metrics/overview.js
- app/src/js/components/locale.js
- app/src/js/paths/index.js
- app/src/js/paths/metrics.js
- app/src/js/utils/format.js
- app/src/js/utils/table-config/metrics.js
**Description**
Implement the v2 metrics endpoint in the dashboard
**Spec**
See Ticket: [EDPUB-1219](https://bugs.earthdata.nasa.gov/browse/EDPUB-1219)
**Validation**
Click on Metrics tab and see the new Metrics table
/metrics
this is the overview table
/metrics/daacs
this will DAAC information table (DAAC Metrics)
/metrics/users (User Metrics)
this with users count
> EDPUB-1219: implement dashboard UI metrics

- app/src/js/components/Requests/overview.js
- app/src/js/components/home.js
- app/src/js/utils/table-config/requests.js
Update submission table to handle auto steps.
A flag is added to the object this function creates to gray out the next step button for given request.
In addition a reload flag can be added that would be set true in the event of a step having an action_id and its last updated timestamp is less than 2 minutes old.  If this flag is true it should cause the active endpoint the be required after a brief delay (~30 Sec).  
See Ticket: [EDPUB-1222](https://bugs.earthdata.nasa.gov/browse/EDPUB-1222)
---
In home page and in requests page if the next action is [Map Question Response To Ummc] or if actionid exists then until the background task is completed we see a greyed out button which can not be clicked.
> EDPUB-1222: Update submission table to handle auto steps.

- app/src/css/_base.scss
- app/src/js/components/DataUpload/overview.js
Add Progress reporting to the upload module and also display an error message if the upload fails
See Ticket: 
[EDPUB-1225](https://bugs.earthdata.nasa.gov/browse/EDPUB-1225)
[EDPUB-1134](https://bugs.earthdata.nasa.gov/browse/EDPUB-1134)
---
1. Click on any requests. 
2. Try uploading a file and check if you see a progress bar.
3. The way I tested the fail condition was to turn off the VPN and check if the upload failed.
> Edpub-1134 Add Progress reporting to the upload module

- CHANGELOG.md
- app/src/css/_base.scss
Fixed zindex on user creation page.
1. Pull branch locally or push out to SIT.
1. Navigate to http://localhost:3000/users/add
1. Expand the Role selection dropdown and verify it looks as expected.
- Fixed zindex on user creation page. (ac975ce87f3d7f4f1e451bb33e8773fd15a7c56c)
> Fixed zindex on user creation page.

- app/src/js/components/DataUpload/overview.js
Updates the verbiage for uploads on the Request Page in the dashboard
See Ticket: https://bugs.earthdata.nasa.gov/browse/EDPUB-1215
---
3. Create a new request
4. Go to the request page and verify the text has updated from “Upload Data File" to "Sample Data and Data Product Documentation File(s): Add or replace file(s)." and has additional context below
---
> Updating upload text

- .env
- CHANGELOG.md
- README.md
- docker-compose.yml
- package-lock.json
Updated help link to getting started overview page on dashboard home
https://bugs.earthdata.nasa.gov/browse/EDPUB-1271
1. Pull locally
1. From forms repo run 'npm run start' to start the api, forms and dashboard (Make sure dashboard re-builds).
1. Log into the dashboard as 'Earthdata Pub System'.
1. Verify the help link on the home page links to getting_started.
1. Push to SIT.
1. Verify there as well.
Updated help link to getting started overview page on dashboard home (c1b0e96e205f4e04b7c5ac5349235934473d3c5e)
> Updated home page help link to getting started overview page

- app/src/css/_base.scss
- app/src/css/_buttons.scss
- app/src/css/vendor/bootstrap/_utils.scss
- app/src/js/actions/index.js
- app/src/js/components/DropDown/DropDown.scss
- app/src/js/components/DropDown/dropdown.js
- app/src/js/components/Forms/overview.js
- app/src/js/components/Groups/index.js
- app/src/js/components/Groups/list.js
- app/src/js/components/Metrics/overview.js
- app/src/js/components/ProcessingModal/ProcessingModal.js
- app/src/js/components/ProcessingModal/ProcessingModal.scss
- app/src/js/components/Questions/index.js
- app/src/js/components/Requests/index.js
- app/src/js/components/Requests/overview.js
- app/src/js/components/Requests/status.js
- app/src/js/components/Roles/overview.js
- app/src/js/components/home.js
- app/src/js/paths/requests.js
- app/src/js/utils/table-config/groups.js
- app/src/js/utils/table-config/metrics.js
- app/src/js/utils/table-config/roles.js
- app/src/js/utils/table-config/users.js
Remove dead code from the dashboard 
See Ticket: [EDPUB-1116](https://bugs.earthdata.nasa.gov/browse/EDPUB-1116)
> Edpub-1116: Removed commented and unwanted code from dashboard

- app/src/js/components/Requests/overview.js
- app/src/js/components/Requests/status.js
- app/src/js/components/Requests/withdrawn.js
- app/src/js/components/home.js
- app/src/js/utils/table-config/requests.js
Update dashboard to use the name field
See Ticket: [EDPUB-1274](https://bugs.earthdata.nasa.gov/browse/EDPUB-1274)
---
Make sure we see the data product and data producer names in all the places where it was previously displayed. Because, we are getting these values from the submission table.
> EDPUB-1274: dashboard side changes for name field

- app/src/js/components/SearchModal/config.js
Update expected return from /api/data/users call to only name
See Ticket:  https://bugs.earthdata.nasa.gov/browse/EDPUB-1285
---
2. Deploy this branch and the corresponding api branch locally.
3. Create a test user with group ASDC and role Data Producer.
4. Use the swagger API docs to test filtering the /api/data/users endpoint based on the group and role id
---
> EDPUB- 1285: Add list users filter by role group

- app/src/js/components/DataUpload/overview.js
- app/src/js/components/Forms/form.js
- dependency_list.txt
- package-lock.json
- package.json
Update upload dependency to point to npm package instead of local file dependency
See Ticket: https://bugs.earthdata.nasa.gov/browse/EDPUB-1305
---
2. Push branch to SIT.
3. Test uploading file within SIT.
---
> EDPUB-1305: Update to upload npm package

- app/src/js/components/Auth/index.js
- app/src/js/utils/auth.js
Hotfix for issue where a user is "authenticated" but not really
> Resolve incomplete user issue

- app/src/js/App.js
- app/src/js/actions/index.js
- app/src/js/components/FormQuestions/DynamicTable.js
- app/src/js/components/FormQuestions/FileUploader.js
- app/src/js/components/FormQuestions/FormQuestions.css
- app/src/js/components/FormQuestions/ScrollToTop.js
- app/src/js/components/FormQuestions/index.js
- app/src/js/components/FormQuestions/questions.js
- app/src/js/components/FormRequest/form.js
- app/src/js/components/FormRequest/index.js
- app/src/js/components/FormRequest/overview.js
- app/src/js/components/Requests/overview.js
- app/src/js/components/Requests/request.js
- app/src/js/components/home.js
- app/src/js/utils/format.js
- app/src/js/utils/table-config/requests.js
- package-lock.json
- package.json
Update Form Application From Vue 2 to React 
See Ticket: [EDPUB-1339](https://bugs.earthdata.nasa.gov/browse/EDPUB-1339)
---
1. Make sure the application works as expected, like how it is working in Vue.js
> Edpub 1313: Update Form Application From Vue 2 to React

- app/src/js/components/FormQuestions/FormQuestions.css
- app/src/js/components/FormQuestions/questions.js
- app/src/js/components/FormRequest/index.js
- app/src/js/components/FormRequest/overview.js
- dependency_list.txt
- package-lock.json
- package.json
Address additional features or fixes based on feedback
See Ticket: [EDPUB-1346](https://bugs.earthdata.nasa.gov/browse/EDPUB-1346)
[EDPUB-1349](https://bugs.earthdata.nasa.gov/browse/EDPUB-1349)
---
1. React forms testing, Datepicker behavior 
2. Create a new request by clicking on an existing request form -> DAAC Selected: -> This redirects to DAAC selection form by checking the DAAC previously selected. 
3. Required text CSS next to question/radio is aligned
4. Cancel button click confirmation popup
5. Added progress bar for upload
> Edpub-1313 and Edpub-1349

- app/src/js/components/Forms/form.js
Add a modal which pops up after adding a reviewer which notifies the user that the reviewer was sent an email notification.
See Ticket: [EDPUB-1351](https://bugs.earthdata.nasa.gov/browse/EDPUB-1351)
---
1.  Select reviewers in EDPub review form
2. Clicking on Add reviewers will send an email notification, and a pop-up will show up with the message that the reviewers are notified.
> EDPUB-1351: Added pop up to confirm the reviewers notification

- app/src/js/components/DataUpload/overview.js
- app/src/js/components/FormQuestions/FormQuestions.css
- app/src/js/components/FormQuestions/questions.js
- app/src/js/components/Forms/form.js
Finalize Multiple File Upload
See Ticket: [EDPUB-1426](https://bugs.earthdata.nasa.gov/browse/EDPUB-1426)
---
1. In  Forms, Request Detail Page, and Group Upload Page, you can drop and drag or select multiple files to upload simultaneously.
2. Make sure you see the file upload progress and works as expected.
> Edpub-1426: Finalize Multiple File Upload

- app/src/js/components/FormQuestions/questions.js
Finalize Multiple File Upload
See Ticket: [EDPUB-1426](https://bugs.earthdata.nasa.gov/browse/EDPUB-1426)
---
In Forms, Request Detail Page, and Group Upload Page, you can drop and drag or select multiple files to upload simultaneously.
Make sure you see the file upload progress and works as expected.
> changed the initial value from 89% to 0%

- app/src/js/components/Questions/overview.js
- app/src/js/utils/table-config/questions.js
Questions table config was checking for wrong permissions for showing edit button
3. Sign in as admin account
4. Navigate to /questions page
5. Validate that edit button column is shown
6. Sign in as DAAC staff account
7. Navigate to /questions page
8. Validate that edit button column is not shown
---
> Hotfix: Fix missing edit column in questions overview

- app/src/js/actions/index.js
- app/src/js/components/Questions/Questions.css
- app/src/js/components/Questions/edit.js
- app/src/js/components/Questions/index.js
- app/src/js/components/Questions/question.js
Creates a dashboard page for adding/editing a question
See Tickets: 
- https://bugs.earthdata.nasa.gov/browse/EDPUB-1403
- https://bugs.earthdata.nasa.gov/browse/EDPUB-1404
Depends on :
- https://github.com/eosdis-nasa/earthdata-pub-dashboard/pull/102
- https://github.com/eosdis-nasa/earthdata-pub-api/pull/154
---
3. Navigate to localhost:3000/questions
4. Click the Add Question button
5. Add information to fields and submit
6. Verify that the form submits and presents you with the results of your added question
7. Navigate back to  localhost:3000/questions
8. In the list choose a question and click Edit
9. Edit the question fields and verify that the returned result shows the updated values
> Edpub 1403 1404 questions dashboard

- app/src/js/actions/index.js
- app/src/js/components/FormQuestions/FormQuestions.css
- app/src/js/components/Forms/edit.js
- app/src/js/components/Forms/index.js
- app/src/js/components/Forms/overview.js
- app/src/js/components/Header/header.js
- app/src/js/utils/privileges.js
- app/src/js/utils/table-config/forms.js
Create Dashboard page for Add/edit form
See Ticket: [EDPUB-1400](https://bugs.earthdata.nasa.gov/browse/EDPUB-1400)
[EDPUB-1399](https://bugs.earthdata.nasa.gov/browse/EDPUB-1399)
---
**I have added Inputs and Forms options in the nav bar for ADMINS** Can be removed later
1. got to baseurl/forms
2. Click on + Add forms to add new forms
3.  Click on Shortname to edit the form 
4.  All fields are mandatory before you submit the form.
> Edpub 1399 & EDPUB-1400: Create Dashboard page for Add/edit form

- app/src/js/actions/index.js
- app/src/js/components/Requests/overview.js
- app/src/js/components/home.js
- app/src/js/utils/table-config/requests.js
Updates the dashboard to handle code validation for publication requests
See Ticket: https://bugs.earthdata.nasa.gov/browse/EDPUB-1450
Related PRs: https://github.com/eosdis-nasa/earthdata-pub-api/pull/171
---
3. Navigate to the dashboard
4. Click "New Request" -> "Data Accession Request"
5. Verify that a new Data Accession Request was initialized
6. Copy the request Id and use it to create a new code in your favorite database visualizer. I.E.
```
INSERT INTO code(submission_id, daac_id) Values('696753a8-49fe-43ed-ae83-70170119000f', 'ef229725-1cad-485e-a72b-a276d2ca3175');
```
7. Copy the newly created code
8. On the dashboard click "New Request" -> "Data Publication Request"
9. Verify form will …
> Updating dashboard to validate publication codes if provided

- app/src/js/App.js
- app/src/js/components/DataDownload/index.js
- app/src/js/components/DataDownload/overview.js
Add Attachment Capabilities to Email Notifications: Add attachment capabilities to email notifications or document limitations / restrictions
See Ticket: [EDPUB-1446](https://bugs.earthdata.nasa.gov/browse/EDPUB-1446)
---
3. Navigate to conversation. Add attachments and send reply.
4. in your mailbox, click on the attachment name if there are any so you can download them now from your EDPUB account after authentication.
> Edpub-1446: Add Attachment Capabilities to Email Notifications

- app/src/js/components/Workflows/edit.js
- app/src/js/components/Workflows/index.css
- app/src/js/components/Workflows/workflow-builder.js
- package-lock.json
- package.json
The interface should allow DAACs to add an existing step to a workflow, remove a step from a workflow, reorganize steps within a workflow. The workflow should implicitly start with an init step and end with a close step. The same interface can be used for creating and editing workflows
See Ticket: [EDPUB-1390](https://bugs.earthdata.nasa.gov/browse/EDPUB-1390)
---
3. Navigate to workflows and add/edit workflows. Create/Edit workflow using a custom workflow builder.
> EDPUB-1390: Create EDPub Workflow Editor Interface

- app/src/js/App.js
- app/src/js/components/Header/header.js
- app/src/js/components/MyMetrics/chart.css
- app/src/js/components/MyMetrics/index.js
- app/src/js/components/MyMetrics/overview.js
- app/src/js/components/locale.js
- app/src/js/paths/index.js
- app/src/js/paths/mymetrics.js
- package-lock.json
- package.json
Stats like a chart analyzing the amount of data published / to which DAAC data was published, etc...
See Ticket: [EDPUB-1449](https://bugs.earthdata.nasa.gov/browse/EDPUB-1449)
---
3. Navigate to MyMetrics and view the chart/Table; ensure all the functionalities work as expected.
> Edpub-1449: Update Internal Metrics Reporting

- CONTRIBUTING.md
- README.md
- app/src/js/actions/index.js
- app/src/js/components/Auth/index.js
- app/src/js/components/FormRequest/form.js
- app/src/js/components/Forms/form.js
- app/src/js/components/Requests/overview.js
- app/src/js/components/home.js
- app/src/js/config/config.js
- cypress.config.js
- cypress/e2e/1-sanity.cy.js
- cypress/e2e/2-login.cy.js
- docker-compose.yml
- webpack.common.js
Remove documentation references to forms repo & old URL
See Ticket: EDPUB-1477
---
3. Log into local dashboard.
4. Create new request
5. Change step to form review
6. Navigate to form review overview page.
---
> EDPUB-1477: Remove Forms References

- app/src/js/components/Conversations/visibility.js
- app/src/js/components/Questions/edit.js
- app/src/js/components/Requests/request.js
- app/src/js/reducers/api.js
- app/src/js/utils/privileges.js
- app/src/js/utils/table-config/requests.js
- app/src/js/utils/table-config/steps.js
Resolve some of the ambiguity in application roles and privileges
See Ticket: https://bugs.earthdata.nasa.gov/browse/EDPUB-1431
---
2. Pull this branch and [dashboard branch](https://github.com/eosdis-nasa/earthdata-pub-api/tree/EDPUB-1431-solidify-roles-and-privileges) locally.
3. Log in as a data producer and work through a typical request workflow.
4. Log in as a DAAC staff and work the above request through a typical request workflow.
5. Ensure that dashboard permissions appear to work as expected.
---
> EDPUB-1431: Solidify roles and privileges

- .gitignore
- .snyk
Resolve pending snyk vulnerabilities or create tickets for unresolvable ones.
JIRA Task: [EDPUB-1471](https://bugs.earthdata.nasa.gov/browse/EDPUB-1471)
and validate the expected behavior. (For an example of good validation instructions, check out [Bryan's Bouncy Ball PR.](https://github.com/sparkbox/bouncy-ball/pull/56#issue-192153701))_
3. Navigate to make sure build doesn't fail when the code changes are pushed to the branch and also, make sure the …
> added ignore for elliptic vulnerability

- app/src/js/components/FormQuestions/DynamicTable.js
- app/src/js/components/FormQuestions/FormQuestions.css
- app/src/js/components/FormQuestions/questions.js
Create New 'Submit Data to an ESDIS DAAC' Form
JIRA Task: https://bugs.earthdata.nasa.gov/browse/EDPUB-1435
and validate the expected behavior. (For an example of good validation instructions, check out [Bryan's Bouncy Ball PR.](https://github.com/sparkbox/bouncy-ball/pull/56#issue-192153701))_
Make sure all merge request checks have …
> Edpub 1435: Create New 'Submit Data to an ESDIS DAAC' Form

- app/src/js/components/MyMetrics/chart.css
- app/src/js/components/MyMetrics/overview.js
Currently MyMetrics page's chart breakdown will link to the various requests by id. This needs to be updated to use request name for a better UI/UX. This will involve updating the API query to send the request name as well as updating the dashboard to reference the request name instead of id.
If the request name is not populated, we will use the same approach as the overview pages of
Request Initialized by <initiator's name>
with a notice at the top of the My Metrics page that this indicates a form's request name field has not yet been populated.
JIRA Task: [EDPUB-1504](https://bugs.earthdata.nasa.gov/browse/EDPUB-1504)
_Put an `x` in the boxes that apply. You can also fill these …
> EDPUB-1504: Update MyMetrics to use request name instead of request id

- app/src/js/components/Requests/overview.js
- app/src/js/components/Workflows/index.css
- app/src/js/components/home.js
Chelsey pointed out that there are some references such as the New Request button -> Data Accession Request which need to be updated to align better with the most recent pivot. My initial thought are "Accession Request" and "Publication Request" describe the process okay; however, we'll need to reach out to info team co-chairs to ensure that aligns with their thoughts.
JIRA Task: [[example](link_here)](https://bugs.earthdata.nasa.gov/browse/EDPUB-1511)
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before …
> EDPUB-1511: Update various dashboard labels

- app/src/css/_base.scss
Change step dropdown orders itself above the add contributor modal creating unpleasant UI/UX
JIRA Task: [[example](link_here)](https://bugs.earthdata.nasa.gov/browse/EDPUB-1537)
and validate the expected behavior. (For an example of good validation instructions, check out [Bryan's Bouncy Ball …
> EDPUB-1537:  Fix change step dropdown visibility ordering

- app/src/js/components/Workflows/edit.js
- app/src/js/components/Workflows/index.css
- app/src/js/components/Workflows/overview.js
- app/src/js/components/Workflows/workflow-builder.js
- app/src/js/components/Workflows/workflow.js
Add confirmation modal after Edit button clicked that says something like "x number of requests are currently using the y workflow and will be affected by this update. Do you wish to continue?" to ensure there is a proper understanding of consequences of workflow editor changes
Update add button to "Add Step" instead of "Add Nodes"
Update ORNL Service Trigger Step - grey while all others are blue if editable
Add warning modal if step which belongs to another workflow is added to current workflow - this is important because the step data (specifically previous step data) will be overwritten
Move form submission fields to left aligned
Increase text area for description
JIRA Task: [[example](link_here)](https://bugs.earthdata.nasa.gov/browse/EDPUB-1549)
What types of changes does your code …
> EDPUB-1549: Update Workflow Editor

- app/src/js/components/Requests/request.js
- app/src/js/components/Review/review.js
- app/src/js/utils/privileges.js
Updates the dashboard to handle the 3 issues identified in the validation of observer visibility
1. All observers can set the current workflow step
2. Observers can see DAR Approval page and have ability to approve
3. DAAC Assignment (Final) link is available to all DAAC Observers
JIRA Task: https://bugs.earthdata.nasa.gov/browse/EDPUB-1509
_This will help us get a jump start on validating your PR by describing the steps to …
> updates to observer visibility based on role/group

- package-lock.json
- package.json
> Hotfix: Misc Reroute Feature Updates

- app/src/js/utils/table-config/requests.js
Removes dev testing id column from request table
3. Validate that the id column of the request table no longer exists
> Hotfix: Remove dev id column

- app/src/js/components/Requests/overview.js
- app/src/js/components/home.js
Update publication code prompt to include instructions and update button formatting.
3. Click new request
4. Click publication request
5. Validate that there are now basic instructions in the prompt and that the button formatting has changed.
> Hotfix: Update publication code prompt

- app/src/js/components/FormQuestions/DynamicTable.js
Update hardcoded value for table control id conditional
3. Create a new accession request.
4. Ensure that the table at the bottom of the DAR is the expected table describing data products.
> Hotfix: Fix form table population

- app/src/js/components/Help/getting_started.js
Added data evaluation request section to left nav area of getting_started page
3. Navigate to the getting_started overview page.
4. Confirm that there is a data evaluation request element in the left navigation.
5. Confirm that clicking the data evaluation request element jumps the page to the DER page section.
> Hotfix: Add Data Evaluation Request section header in left nav area

- app/src/js/components/Forms/form.js
If a user navigates to the url of a request form review that doesn't exist, the user gets a runtime error like 'Cannot read properties of undefined (reading 'includes')' instead the user should be redirected to the standard 404 page. The developer can test locally by attempting to access http://localhost:3000/forms/id/6c544723-241c-4896-a38c-adbc0a364293?requestId=fd459019-bec4-43e7-a15a-8e88a79bbcef
JIRA Task: (https://bugs.earthdata.nasa.gov/browse/EDPUB-1538)
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look …
> EDPUB-1538:  Fix form redirect if request id DNE

- app/src/js/components/Comments/comments.js
- app/src/js/components/Conversations/attachment.js
- app/src/js/components/Conversations/conversation.js
- app/src/js/components/Conversations/visibility.js
- app/src/js/components/DataUpload/customUpload.js
- app/src/js/components/Forms/form.js
Add attachment capability to step comments
JIRA Task: https://bugs.earthdata.nasa.gov/browse/EDPUB-1531
3. Create a new accession request.
4. Change the current step to the DAR form review.
5. Leave a comment with an attachment.
6. Validate that a tooltip saying the attachment is unavailable appears after sending.
7. Refresh the page.
8. Validate that the attachment is now available for download.
9. Validate you can download the attachment by clicking on it.
> EDPUB-1531: Add attachments to step comments

- app/src/js/components/Conversations/conversation.js
If a user adds a visibility restriction to an existing note, I don't think it is doing the same check of whether the user includes themselves as the reply functionality is. This means, the user may add a visibility restriction to an existing note which doesn't include themselves and lose visibility of the note.
JIRA Task: [[example](link_here)](https://bugs.earthdata.nasa.gov/browse/EDPUB-1530)
_This will help us get a jump start on …
> Fix visibility addition to existing note

- .snyk
- app/src/js/components/Forms/form.js
- package-lock.json
- package.json
Fix File Upload sections on form approval pages to properly separate files by category. If you upload a file to a category on the DAR form it properly seperates the files. On the approval page, however, that file is listed in both upload sections
JIRA Task: https://bugs.earthdata.nasa.gov/browse/EDPUB-1552
and validate the expected …
> Edpub 1552: Fix file list on form review dashboard pages

- app/src/js/components/FormQuestions/questions.js
Update dashboard to include moving scroll/focus to input causing error on error validation
JIRA Task: https://bugs.earthdata.nasa.gov/browse/EDPUB-1574
and validate the expected behavior. (For an example of good validation instructions, check out [Bryan's Bouncy Ball PR.](https://github.com/sparkbox/bouncy-ball/pull/56#issue-192153701))_ …
> EDPUB-1574: Update dashboard to include moving scroll/focus to input causing err

- app/src/js/components/MyMetrics/overview.js
- app/src/js/components/Requests/overview.js
- app/src/js/components/Requests/request.js
- app/src/js/components/Requests/status.js
- app/src/js/components/Requests/withdrawn.js
- app/src/js/components/home.js
- app/src/js/utils/table-config/requests.js
Update Data Product Name and Data Producer Name columns to generalized terminology for DAR/DER/DPR references
JIRA Task: https://bugs.earthdata.nasa.gov/browse/EDPUB-1575
and validate the expected behavior. (For an example of good validation instructions, check out [Bryan's Bouncy Ball …
> EDPUB-1575: Update Data Product Name and Data Producer Name

- app/src/js/components/FormQuestions/questions.js
Update the spatial_vertical_details_upper and spatial_vertical_details_lower inputs in the API to remove the minimum value restricting input.
JIRA Task: [EDPUB-1567](https://bugs.earthdata.nasa.gov/browse/EDPUB-1567)
and validate the expected behavior. (For an example of good validation instructions, …
> EDPUB-1567: Update ‘Upper and Lower Limits’ Inputs to Remove Minimum Value

- app/src/js/components/Table/Metadata.js
Hotfix for the page break
JIRA Task: [EDPUB-1601](https://bugs.earthdata.nasa.gov/browse/EDPUB-1601)
and validate the expected behavior. (For an example of good validation instructions, check out [Bryan's Bouncy Ball PR.](https://github.com/sparkbox/bouncy-ball/pull/56#issue-192153701))_
1. Make sure all …
> EDPUB-1601: Check if array or not

- app/src/template.html
Icons started missing from all environments. Upon investigation, it looks like the id EDPub was previously using may have been rescoped to no longer allow, EDPub origin. I've created a new EDPub development based id for use in all environments.
3. Ensure icons appear when navigating around website.
> Hotfix: Update fontawesome kit id

- app/src/js/components/Requests/additional_review.js
Occasionally, the forms overview section will be present for a manual action step. It is out of place and not useful to users. This issues may be caused by overloading the 'review' step type. Investigate if there is another approach that would align better with expected UI/UX.
JIRA Task: [EDPUB-1617](https://bugs.earthdata.nasa.gov/browse/EDPUB-1617)
_This will help us get a jump start on …
> EDPUB-1617: Remove forms overview section from manual action step pages
